In [3]:
#!/
import numpy as np

# print(dir(np))
arr = np.array([[1,2,3],[4,5,6]], np.int8)


arr.strides
arr.ndim
arr.data

arr.itemsize
arr.nbytes
arr.base

arr.real

arr.imag

arr.flat


arr.tobytes()
arr.squeeze()

new_arr = np.arange(1,37).reshape((3, 6 ,2))

# print(new_arr)

new_arr.sum(axis=0)
new_arr.max(axis=0)

arr = np.arange(50)
arr.std()



a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]], np.int16)
print(a)

a[0][0]

a.ndim #2 dimensions
 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2

In [4]:
#Three dimensional array
array_2d = np.array([[ 1,2,4 ], [5,6,7]])
print(array_2d.ndim)
array_3d = np.array([
	[ [ 1,2,3 ], [4,5,6] ],
	[ [7,8,9], [10,11,12] ]
	])
print(array_3d)
print(array_3d.shape)

array_3d[1]
array_3d.shape

2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


(2, 2, 3)

In [164]:
## Create a basic array
np.zeros(2)

array([0., 0.])

In [175]:
np.ones(5, dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [170]:
np.empty(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [173]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [177]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [180]:
arr = np.array([2,1,5,8,5,3,9])
np.sort(arr)

array([1, 2, 3, 5, 5, 8, 9])

In [19]:
import scipy;
import matplotlib.pyplot as plt
speed_of_light = scipy.constants.speed_of_light
speed_of_light
# plt.imshow(img)


299792458.0