## Tensor can be created directly from torch.tensor(data)

In [2]:
import torch
import numpy as np
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


## Tensor can also be created from numpy and vice versa .. ?

In [8]:
numpy_array = np.array(data)
x_np = torch.from_numpy(numpy_array)
print(f"numpy_array:\n {numpy_array}\n torch from numpy:\n{x_np}")

numpy_array:
 [[1 2]
 [3 4]]
 torch from numpy:
tensor([[1, 2],
        [3, 4]])
